# Exploring plasticity in temperature response

A simple mathematical model to explore acclimatization in temperature response functions. I will test three hypothesis:

1. Plasticity is a genetic predisposition towards wide niche with and has a permanent metabolic cost, e.g. due to maintaining genome and proteins
2. Plasticity is induced by experiencing temperature different from the optima and the metabolic cost is proportional to the LEVEL of acclimatization.
3. Plasticity is induced by experiencing temperature different from the optima and the metabolic cost is proportional to the RATE of acclimatization.

I will explore each hypothesis below. For simplicity I will use a quadratic temperature response with the general temperature response as 

$$\left(1-\left(\frac{T-z}{w}\right)^2 \right) ae^{k*T}$$

I also define $p$ as the level of acclimatization measured as deviance from the optimal temperature $z$.

In [53]:
using SymPy
using Plots
plotlyjs()
@syms T z p c w a k popt v

(T,z,p,c,w,a,k,popt,v)

## Permanent metabolic cost

Lets assume that higher niche width, $w$ creates a metabolic cost $c w^2$. This makes the prediction that there MUST be a tradeoff in niche width and maximum growth. Sympy does rearange the equation so I add it here for clarity:

$$\left(1-\left(\frac{T-z}{w}\right)^2 \right) ae^{k*T} - c w^2$$


First I define the funciton symbolically:

In [56]:
@syms b
H1=(a*e^(k*T))*(1-((T-z)/(w))^2)-c*w^2

  ⎛           2⎞            
  ⎜    (T - z) ⎟  T⋅k      2
a⋅⎜1 - ────────⎟⋅ℯ    - c⋅w 
  ⎜        2   ⎟            
  ⎝       w    ⎠            

and then solve for the optimal niche width, $w_{opt}$

In [57]:
DiffH1=diff(H1,w)
wOptH1=solve(DiffH1,w)

4-element Array{SymPy.Sym,1}
⎡        ______________________________________⎤
⎢       ╱  2    T⋅k            T⋅k      2  T⋅k ⎥
⎢      ╱  T ⋅a⋅ℯ      2⋅T⋅a⋅z⋅ℯ      a⋅z ⋅ℯ    ⎥
⎢-ⅈ⋅4 ╱   ───────── - ──────────── + ───────── ⎥
⎢   ╲╱        c            c             c     ⎥
⎢                                              ⎥
⎢       ______________________________________ ⎥
⎢      ╱  2    T⋅k            T⋅k      2  T⋅k  ⎥
⎢     ╱  T ⋅a⋅ℯ      2⋅T⋅a⋅z⋅ℯ      a⋅z ⋅ℯ     ⎥
⎢ⅈ⋅4 ╱   ───────── - ──────────── + ─────────  ⎥
⎢  ╲╱        c            c             c      ⎥
⎢                                              ⎥
⎢       ______________________________________ ⎥
⎢      ╱  2    T⋅k            T⋅k      2  T⋅k  ⎥
⎢     ╱  T ⋅a⋅ℯ      2⋅T⋅a⋅z⋅ℯ      a⋅z ⋅ℯ     ⎥
⎢ -4 ╱   ───────── - ──────────── + ─────────  ⎥
⎢  ╲╱        c            c             c      ⎥
⎢                                              ⎥
⎢      ______________________________________  ⎥
⎢     ╱  2    T⋅k            T⋅k      2 

Only one solution makes sense (real positive). So lets plot this

In [4]:
function fH1(T,c)
    a=0.23
    k=0.063
    z=20
    gT=a.*exp(T.*k)
    (gT.*((T.^2)/c-2*T*z/c+z^2/c)).^(1/4)
end
Temperature=linspace(0,40,500)
y=fH1(Temperature,0.05)
plot(20-Temperature,y,xlabel="Temperature difference", ylabel="Temp width", label="c=0.05")
y=fH1(Temperature,0.01)
plot!(20-Temperature,y,xlabel="Temperature difference", ylabel="Temp width", label="c=0.01")
y=fH1(Temperature,0.1)
plot!(20-Temperature,y,xlabel="Temperature difference", ylabel="Temp width", label="c=0.1")
#savefig("/Users/raukhur/Documents/ecmwf/media/OptWidth.png")

### Conclusions H1

1. Obviously, if you are at your optimal temperature you don't need niche width
2. If you live in an fluctuating environment then on average you need higher $w$, one could probably make some smart calculation assuming normally distributed variance around the optima....
3. May have support from your data with environmental variability

## Metabolic cost is proportional to the LEVEL of acclimatization

Here I assume that there is a dyanmic acclimatization variable $p$ that can change your temperature optima $z$ and that $p_{opt}$ is the optimal acclimatization. The equation looks as follows:

$$\left(1-\left(\frac{T-(z+p)}{w}\right)^2 \right) a*e^{k*T}-c*p^2$$

again I define it symbolically:

In [5]:
H2=(a*e^(k*T))*(1-((T-(z+p))/w)^2)-c*p^2

  ⎛               2⎞            
  ⎜    (T - p - z) ⎟  T⋅k      2
a⋅⎜1 - ────────────⎟⋅ℯ    - c⋅p 
  ⎜          2     ⎟            
  ⎝         w      ⎠            

and solve for the optimal level of acclimatization:

In [6]:
DiffH2=diff(H2,p)
pOptH2=solve(DiffH2,p)

1-element Array{SymPy.Sym,1}
⎡           T⋅k⎤
⎢a⋅(T - z)⋅ℯ   ⎥
⎢──────────────⎥
⎢   T⋅k      2 ⎥
⎣a⋅ℯ    + c⋅w  ⎦

Again, lets plot this result:

In [7]:
function DPC(T,z,w,c)
    (T-z).*exp(T*0.0638)./(c*w^2+exp(T.*0.0638))
end
plot(Temperature-20,DPC(Temperature,20,10,0.01))
plot!(Temperature-20,DPC(Temperature,20,10,0.05),xlabel="Temperature difference", ylabel="acclimatization parameter")

This is pretty cool, but what happens if we substitute the optimal acclimatixation $p_{opt}$ back into the function, essentially what we would measure in most experiments where the acclimatization effect has already occured?

In [8]:
function fH2(T,c,z)
    a=0.23
    k=0.063
    w=10
    gT=a.*exp(T.*k)
    return gT.*(1-((T-(z+DPC(T,z,w,c)))./w).^2)-c.*DPC(T,z,w,c).^2
end
N=5
c=logspace(-2.5,-1.5,N)
    a=0.23
    k=0.063
plot(Temperature-20,fH2(Temperature,c[1],20.0), ylim=(0.0, 1.5))
plot!(Temperature-20,fH2(Temperature,c[2],20.0), ylim=(0.0, 1.5))
plot!(Temperature-20,fH2(Temperature,c[3],20.0), ylim=(0.0, 1.5))
plot!(Temperature-20,fH2(Temperature,c[4],20.0), ylim=(0.0, 1.5))
plot!(Temperature-20,fH2(Temperature,c[5],20.0), ylim=(0.0, 1.5))
plot!(Temperature-20,a.*exp(Temperature.*k), c=:black)

ok, this is neat! Being able to acclimatize does NOT change the maximum growth at optimal temperature $z$ but changes the width of the response. This is more akin to your data I suspect. 

### Conclusions

1. A permanent metabolic cost of being acclimatized does NOT change maximum growth
2. A permanent metabolic cost of being acclimatized translates into wider $w$ (I think one can prove that analytically, I did it without the general temperature response)
3. A permanent cost of being acclimatized constrains the optimal level of acclimatization ($p_{opt}$ is defined)

## Metabolic cost is proportional to the RATE of acclimatization

For this hypothesis we make p dynamic as 

$$\frac{dp}{dt}=v \left( p_{opt}-p\right)$$

and add the metabolic cost proportional to the square value of $\frac{dp}{dt}$ to reflect a cost that only occurs when you have to change p. The full equation looks as:

$$\left(1-\left(\frac{T-(z+p)}{w}\right)^2 \right) a*e^{k*T}-c*\left(\frac{dp}{dt}\right)^2$$

and we go through the procedure again to find $p_{opt}$

In [9]:
dp=v*(popt-p)

v⋅(-p + popt)

In [10]:
H3=(a*e^(k*T))*(1-((T-(z+p))/w)^2)-c*dp^2

5-element Array{SymPy.Sym,1}
⎡                                             ⎛               2⎞         ⎤
⎢                       2            2        ⎜    (T - p - z) ⎟  0.063⋅T⎥
⎢- 0.00316227766016838⋅v ⋅(-p + popt)  + 0.23⋅⎜1 - ────────────⎟⋅ℯ       ⎥
⎢                                             ⎜          2     ⎟         ⎥
⎢                                             ⎝         w      ⎠         ⎥
⎢                                                                        ⎥
⎢                                             ⎛               2⎞         ⎥
⎢                       2            2        ⎜    (T - p - z) ⎟  0.063⋅T⎥
⎢- 0.00562341325190349⋅v ⋅(-p + popt)  + 0.23⋅⎜1 - ────────────⎟⋅ℯ       ⎥
⎢                                             ⎜          2     ⎟         ⎥
⎢                                             ⎝         w      ⎠         ⎥
⎢                                                                        ⎥
⎢                                     ⎛               2⎞               

In [11]:
DiffH3=diff(H3,p)
#subs(DiffChangeCost,popt,p)
pOptH3=solve(subs(DiffH3,popt,p),p)

Dict{SymPy.Sym,SymPy.Sym} with 1 entry:
  p => T - z

right, this says you'd better adapt to whatever the current temperature is. No restraints....

One can imagine the restraint being the amount of genetic information for proteins with different temperature tolerances. So, assume we put in a constraint to the range of $p$ provided by genetic information as $p_{range}=\left[T_{low}, T_{high}\right]$

In [26]:
prange=[-1 1;-3 3; -6 6]
function DPCp(T,z,w,c,p,dp)
    0.23*exp(T*0.0638).*(1-((T-(z+p))/w).^2)-c*dp^2
end
endTime=1000
N=400
y=zeros(Float64,endTime,N,3)
p=zeros(Float64,endTime,N,3)
dp=zeros(Float64,endTime,N,3)
newTemp=25.0
Temperature=linspace(0,40,N)

for q=1:N
    for t=1:endTime-1
        for i=1:3
            dp[t,q,i]=0.01*((Temperature[q]-20.0)-p[t,q,i])
            if p[t,q,i]>prange[i,2] || p[t,q,i]<prange[i,1]
                dp[t,q,i]=0.0
            end
            y[t,q,i]=DPCp(Temperature[q],20.0,10.0,100.0,p[t,q,i],dp[t,q,i])
            
            p[t+1,q,i]=min(prange[i,2],max(prange[i,1],p[t,q,i]+dp[t,q,i]))
        end
    end
    
end



Below follow the time evolution for three species with different temperature range constraints for acclimatization, blue=[-1 1], orange=[-3 3] and red=[-6 6]

In [13]:
Time=1
plot(collect(Temperature),y[Time,:,1], ylim=(0.0, 1.5))
plot!(collect(Temperature),y[Time,:,2],c=:orange)
plot!(collect(Temperature),y[Time,:,3], c=:red)
plot!(collect(Temperature),0.23*exp(collect(Temperature).*0.0638), c=:black)


In [14]:
Time=30
plot(collect(Temperature),y[Time,:,1], ylim=(0.0, 1.5))
plot!(collect(Temperature),y[Time,:,2],c=:orange)
plot!(collect(Temperature),y[Time,:,3], c=:red)
plot!(collect(Temperature),0.23*exp(collect(Temperature).*0.0638), c=:black)


In [15]:
Time=60
plot(collect(Temperature),y[Time,:,1], ylim=(0.0, 1.5))
plot!(collect(Temperature),y[Time,:,2],c=:orange)
plot!(collect(Temperature),y[Time,:,3], c=:red)
plot!(collect(Temperature),0.23*exp(collect(Temperature).*0.0638), c=:black)


In [16]:
Time=90
plot(collect(Temperature),y[Time,:,1], ylim=(0.0, 1.5))
plot!(collect(Temperature),y[Time,:,2],c=:orange)
plot!(collect(Temperature),y[Time,:,3], c=:red)
plot!(collect(Temperature),0.23*exp(collect(Temperature).*0.0638), c=:black)


In [17]:
Time=999
plot(collect(Temperature),y[Time,:,1], ylim=(0.0, 1.5))
plot!(collect(Temperature),y[Time,:,2],c=:orange)
plot!(collect(Temperature),y[Time,:,3], c=:red)
plot!(collect(Temperature),0.23*exp(collect(Temperature).*0.0638), c=:black)


So you can note that the ranges start to expand but initially there is a metabolic cost making the curves slope from the optimum. First after equilibrium acclimatication has occured (time=999) the slopes approach the general temperature response again. From experimental data studing this effect over time one might be able to find support for either of these hypothesis, maybe the reality is a mix between them though.

### Conclusion

1. The end temperature response has a part that is concave rather than convex
2. The transition goes from widening to this shape.
3. The dynamics are heavily subject to range and change cost prameters, I have choosen something that looks nice here

In [41]:
gr()
anim=@animate for Time=1:200
    plot(collect(Temperature),y[Time,:,1], ylim=(0.0, 1.5), title="Time: "*string(Time), label="[-1 1]", xlabel="Experienced Temperature", ylabel="growth rate")
    plot!(collect(Temperature),y[Time,:,2],c=:orange, label="[-3 3]")
    plot!(collect(Temperature),y[Time,:,3], c=:red, label="[-6 6]")
    plot!(collect(Temperature),0.23*exp(collect(Temperature).*0.0638), c=:black, label="General Temp response", legend=false)
end

Plots.Animation("/var/folders/x_/3brnnyx14kd80hz2ycynyrtw0000gn/T/tmpkQ7KwX",String["000001.png","000002.png","000003.png","000004.png","000005.png","000006.png","000007.png","000008.png","000009.png","000010.png"  …  "000191.png","000192.png","000193.png","000194.png","000195.png","000196.png","000197.png","000198.png","000199.png","000200.png"])

In [42]:
gif(anim, "Tempanim_fps15.gif", fps = 15)

INFO: Saved animation to /Users/raukhur/Google Drive/code/julia/Tempanim_fps15.gif


Plots.AnimatedGif("/Users/raukhur/Google Drive/code/julia/Tempanim_fps15.gif")

![](Tempanim_fps15.gif)

In [46]:
prange=[-1 1;-3 3; -6 6]
function DPCp(T,z,w,c,p,dp)
    0.23*exp(T*0.0638).*(1-((T-(z+p))/w).^2)-c*dp^2
end
endTime=1000
N=400
y=zeros(Float64,endTime,N,3)
p=zeros(Float64,endTime,N,3)
dp=zeros(Float64,endTime,N,3)
newTemp=25.0
Temperature=linspace(0,40,N)

for q=1:N
    for t=1:endTime-1
        T=20.0+5*sin(t*2*pi/330)
        for i=1:3
            dp[t,q,i]=0.01*((Temperature[q]-T)-p[t,q,i])
            if p[t,q,i]>prange[i,2] || p[t,q,i]<prange[i,1]
                dp[t,q,i]=0.0
            end
            y[t,q,i]=DPCp(Temperature[q],T,10.0,100.0,p[t,q,i],dp[t,q,i])
            
            p[t+1,q,i]=min(prange[i,2],max(prange[i,1],p[t,q,i]+dp[t,q,i]))
        end
    end
    
end


In [49]:
anim=@animate for Time=1:1000
    plot(collect(Temperature),y[Time,:,1], ylim=(0.0, 1.5), title="Time: "*string(Time), label="[-1 1]", xlabel="Experienced Temperature", ylabel="growth rate")
    plot!(collect(Temperature),y[Time,:,2],c=:orange, label="[-3 3]")
    plot!(collect(Temperature),y[Time,:,3], c=:red, label="[-6 6]")
    plot!(collect(Temperature),0.23*exp(collect(Temperature).*0.0638), c=:black, label="General Temp response", legend=false)
end

Plots.Animation("/var/folders/x_/3brnnyx14kd80hz2ycynyrtw0000gn/T/tmpsiI9pU",String["000001.png","000002.png","000003.png","000004.png","000005.png","000006.png","000007.png","000008.png","000009.png","000010.png"  …  "000991.png","000992.png","000993.png","000994.png","000995.png","000996.png","000997.png","000998.png","000999.png","001000.png"])

In [50]:
gif(anim, "TempanimVar_fps15.gif", fps = 15)

INFO: Saved animation to /Users/raukhur/Google Drive/code/julia/TempanimVar_fps15.gif


Plots.AnimatedGif("/Users/raukhur/Google Drive/code/julia/TempanimVar_fps15.gif")